---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-redirect
  namespace: istio-system
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
